name: registry
home: https://github.com/drycc/registry
apiVersion: v2
dependencies:
  - name: common
    repository: https://charts.drycc.cc/stable
    version: 1.x.x
description: Docker registry for Drycc Workflow.
maintainers:
  - name: Drycc Team
    email: engineering@drycc.com
version: v1.1.0
