imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"
# limitsCpu: "100m"
# limitsMemory: "50Mi"
concurrencyPolicy: "Replace"

# Service
service:
  # Provide any additional service annotations
  annotations: {}