imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"
# limitsCpu: "100m"
# limitsMemory: "50Mi"
nodeAffinityPreset:
  key: "drycc.cc/node"
  type: "soft"
  values:
  - "true"

podAffinityPreset:
  key: "security"
  type: ""
  values:
  - "drycc-security"

podAntiAffinityPreset:
  key: "app"
  type: "soft"
  values:
  - "drycc-registry"

# registry replicas
replicas: 1

concurrencyPolicy: "Replace"

# Service
service:
  # Provide any additional service annotations
  annotations: {}