imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"
# limitsCpu: "100m"
# limitsMemory: "50Mi"

## Enable diagnostic mode
##
diagnosticMode:
  ## @param diagnosticMode.enabled Enable diagnostic mode (all probes will be disabled and the command will be overridden)
  ##
  enabled: false
  ## @param diagnosticMode.command Command to override all containers
  ##
  command:
    - sleep
  ## @param diagnosticMode.args Args to override all containers
  ##
  args:
    - infinity

nodeAffinityPreset:
  key: "drycc.cc/node"
  type: "soft"
  values:
  - "true"

podAffinityPreset:
  type: ""
  extraMatchLabels:
    security: "drycc-security"

podAntiAffinityPreset:
  type: "soft"
  extraMatchLabels:
    app: "drycc-registry"

# registry replicas
replicas: 1
# registry storage redirect
redirect: "false"
# host port for the registry proxy in the daemonset
proxyPort: 5555

concurrencyPolicy: "Replace"

# The following parameters will no longer use the built-in storage component.
storageLookup: "auto"
storageBucket: "builder"
storageEndpoint: ""
storageAccesskey: ""
storageSecretkey: ""

storage:
  enabled: true

# Service
service:
  # Provide any additional service annotations
  annotations: {}
