apiVersion: v1
kind: Service
metadata:
  name: drycc-registry
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
spec:
  clusterIP: None
  selector:
    app: drycc-registry
  sessionAffinity: ClientIP  
