{{- if eq .Values.global.registryLocation "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-registry
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
spec:
  clusterIP: None
  selector:
    app: drycc-registry
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  sessionAffinity: ClientIP  
{{- end }}
