
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  labels:
    heritage: drycc
  annotations:
    drycc.cc/registry-location: "{{ .Values.global.registryLocation }}"
type: Opaque
data:
  {{- if ne .Values.global.registryLocation "on-cluster" }}
  host: {{ print "drycc-registry" .Release.Namespace  ".svc." .Values.global.clusterDomain | b64enc }}
  secret: {{ randAlphaNum 32 | b64enc }}
  {{- else }}
  host: {{ .Values.host | b64enc }}
  organization: {{ .Values.organization | b64enc }}
  {{- end }}
  username: {{ if .Values.username | default "" | ne "" }}{{ .Values.username | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  password: {{ if .Values.password | default "" | ne "" }}{{ .Values.password | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  redirect: {{ .Values.redirect | b64enc }}
