{{- if eq .Values.global.registryLocation "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-registry
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: drycc-registry
  sessionAffinity: ClientIP  
{{- end }}
