{{- if eq .Values.global.registry_location "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-registry
  labels:
    heritage: drycc
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: drycc-registry
  sessionAffinity: ClientIP  
{{- end }}
