{{- if eq .Values.global.registryLocation "on-cluster" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: drycc-registry-cronjob-daily
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccount: drycc-controller
          initContainers:
          - name: drycc-registry-init
            image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/python-dev:latest
            imagePullPolicy: {{.Values.imagePullPolicy}}
            args:
            - netcat
            - -v
            - -u
            - $(DRYCC_STORAGE_ENDPOINT)
            {{- include "registry.envs" . | indent 12 }}
          containers:
          - image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/registry:{{.Values.imageTag}}
            imagePullPolicy: {{.Values.imagePullPolicy}}
            name: drycc-registry-garbage-collect
            {{- if .Values.diagnosticMode.enabled }}
            command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 14 }}
            args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 14 }}
            {{- else }}
            args:
            - /bin/boot
            - garbage-collect
            - $(DRYCC_REGISTRY_CONFIG)
            - --dry-run
            - --delete-untagged
            {{- end }}
            {{- include "registry.envs" . | indent 12 }}
{{- end }}
