{{- if eq .Values.global.registryLocation "on-cluster" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-registry
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: drycc-registry
  template:
    metadata:
      labels:
        app: drycc-registry
    spec:
      {{- include "common.affinities.pods.soft" (dict "key" "app" "values" (list "drycc-registry")) | indent 6 }}
      serviceAccount: drycc-registry
      initContainers:
      - name: drycc-registry-init
        image: registry.drycc.cc/drycc/python-dev:latest
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
          - netcat
          - -v
          - -a
          - $(DRYCC_MINIO_SERVICE_HOST):$(DRYCC_MINIO_SERVICE_PORT)
      containers:
      - name: drycc-registry
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/registry:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
{{- if or (.Values.limitsCpu) (.Values.limitsMemory)}}
        resources:
          limits:
{{- if (.Values.limitsCpu) }}
            cpu: {{.Values.limitsCpu}}
{{- end}}
{{- if (.Values.limitsMemory) }}
            memory: {{.Values.limitsMemory}}
{{- end}}
{{- end}}
        livenessProbe:
          httpGet:
            path: /v2/
            port: 5000
          initialDelaySeconds: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /v2/
            port: 5000
          initialDelaySeconds: 1
          timeoutSeconds: 1
        env:
          - name: REGISTRY_STORAGE_DELETE_ENABLED
            value: "true"
          - name: REGISTRY_LOG_LEVEL
            value: info
        ports:
          - containerPort: 5000
        volumeMounts:
          - name: registry-storage
            mountPath: /var/lib/registry
          - name: objectstorage-creds
            mountPath: /var/run/secrets/drycc/objectstore/creds
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
      volumes:
        - name: registry-storage
          emptyDir: {}
        - name: objectstorage-creds
          secret:
            secretName: objectstorage-keyfile
{{- end }}
