apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  labels:
    heritage: drycc
type: Opaque
data:
  secret: {{ include "common.secrets.lookup" (dict "secret" "registry-secret" "key" "secret" "defaultValue" (randAlphaNum 32) "context" $) }}
  username: {{ include "common.secrets.lookup" (dict "secret" "registry-secret" "key" "username" "defaultValue" (.Values.username | default (randAlphaNum 32)) "context" $) }}
  password: {{ include "common.secrets.lookup" (dict "secret" "registry-secret" "key" "password" "defaultValue" (.Values.password | default (randAlphaNum 32)) "context" $) }}
  redirect: {{ .Values.redirect | b64enc }}
  {{- if (.Values.storageEndpoint) }}
  storage-lookup: {{ .Values.storageLookup | b64enc }}
  storage-bucket: {{ .Values.storageBucket | b64enc }}
  storage-endpoint: {{ .Values.storageEndpoint | b64enc }}
  storage-accesskey: {{ .Values.storageAccesskey | b64enc }}
  storage-secretkey: {{ .Values.storageSecretkey | b64enc }}
  {{- end }}
